### ISSUE TITLE
Please specify the license

### ISSUE THREAD

**Issue by StSav012** [MahBoiTranslator/TiberianSunRu#2]
Thank you for the outstanding work.

How do you license it? How can I use the data? May I legally create a derivative work?

**Comment by MahBoiDeveloper** [comment]
> Thank you for the outstanding work.
> How do you license it? How can I use the data? May I legally create a derivative work?

Спасибо за интересный вопрос. На текущий момент все мои проекты локализаций распространяются под лицензией `CC-BY-NC`, чтобы не противоречить [EA Modding Guidelines](https://www.ea.com/ru-ru/games/command-and-conquer/command-and-conquer-remastered/modding-faq). Вы можете делать с файлами в репозитории всё, что Вам угодно, пока Вы не продаёте русификаторы и указываете автора.
